In [1]:
import numpy as np

# Task 1

In [2]:
a = np.array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])
a

array([13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

# Task 2

In [3]:
a1 = a.reshape(3, 4)
a1

array([[13, 14, 15, 16],
       [17, 18, 19, 20],
       [21, 22, 23, 24]])

In [4]:
a2 = a[4:8]
a2 = a2.reshape(2, 2)
a2

array([[17, 18],
       [19, 20]])

In [5]:
a3 = a.reshape(2, 6)
a3

array([[13, 14, 15, 16, 17, 18],
       [19, 20, 21, 22, 23, 24]])

In [6]:
a4 = a.reshape(6, 2)
a4

array([[13, 14],
       [15, 16],
       [17, 18],
       [19, 20],
       [21, 22],
       [23, 24]])

In [7]:
a5 = a.reshape(4, 3)
a5

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21],
       [22, 23, 24]])

# Task 3

In [8]:
a6 = a[:6]
a6 = a6.reshape(2, -1)
a6

array([[13, 14, 15],
       [16, 17, 18]])

In [9]:
a7 = a[:8]
a7 = a7.reshape(4, -1)
a7

array([[13, 14],
       [15, 16],
       [17, 18],
       [19, 20]])

In [10]:
a8 = a[:9]
a8 = a8.reshape(3, -1)
a8

array([[13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [11]:
a9 = a[2:12]
a9 = a9.reshape(-1, 5)
a9

array([[15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [12]:
a10 = a[4:12]
a10 = a10.reshape(-1, 4)
a10

array([[17, 18, 19, 20],
       [21, 22, 23, 24]])

# Task 4

НетЪ? =)  (Если я правильно понимаю, его можно транспонировать, значит - он думерный)

# Task 5

In [13]:
b = np.random.randn(3, 4)
b

array([[-0.08488835,  1.83413509, -0.9008379 ,  0.59152184],
       [ 0.93753468,  0.12832263, -0.26288534, -0.043909  ],
       [-1.45875025,  0.6126624 ,  0.05365503,  0.26097997]])

In [14]:
c = b.flatten() 
c

array([-0.08488835,  1.83413509, -0.9008379 ,  0.59152184,  0.93753468,
        0.12832263, -0.26288534, -0.043909  , -1.45875025,  0.6126624 ,
        0.05365503,  0.26097997])

# Task 6

In [15]:
a = np.arange(2, 22, 2)
a = a[::-1]
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

# Task 7

In [16]:
b = a.reshape(-1, 1)
b
# a - одномерный, b - двумерный (можно транспонировать)

array([[20],
       [18],
       [16],
       [14],
       [12],
       [10],
       [ 8],
       [ 6],
       [ 4],
       [ 2]])

# Task 8

In [17]:
a = np.zeros((3, 2))
b = np.ones((2, 2))
b, a

(array([[1., 1.],
        [1., 1.]]),
 array([[0., 0.],
        [0., 0.],
        [0., 0.]]))

In [18]:
v = np.concatenate((a, b), axis=0)
v

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

# Task 9

In [19]:
a = np.arange(0, 12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [20]:
A = a.reshape(4, 3)
A

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [21]:
At = np.transpose(A)
At

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

In [22]:
B = A.dot(At)
B, np.linalg.det(B)

(array([[  5,  14,  23,  32],
        [ 14,  50,  86, 122],
        [ 23,  86, 149, 212],
        [ 32, 122, 212, 302]]),
 0.0)

Обратной не сущетсвует, т.к. определитель равен нулю по определению. ))

# Task 10

In [23]:
np.random.seed(42)
a = np.random.randn(3)*10
np.around(a)

array([ 5., -1.,  6.])

# Task 11

In [24]:
a = np.arange(0, 16)
np.random.shuffle(a)
a

array([ 0, 12, 14,  1,  8,  5, 13,  3,  4,  7, 11, 10, 15,  2,  9,  6])

# Task 12

In [25]:
C = a.reshape(4, 4)
D = C + B*10
D

array([[  50,  152,  244,  321],
       [ 148,  505,  873, 1223],
       [ 234,  867, 1501, 2130],
       [ 335, 1222, 2129, 3026]])

In [26]:
np.linalg.det(D)

-326629.99999999435

In [27]:
D_inv = np.linalg.inv(D)
D_inv

array([[ 0.54686649, -0.65258856, -0.72888283,  0.71880109],
       [ 0.48978661, -0.62509567, -0.4404525 ,  0.51071855],
       [-0.98409515,  1.2901295 ,  1.1233965 , -1.20778863],
       [ 0.43404464, -0.58301442, -0.531825  ,  0.5642715 ]])

In [28]:
np.linalg.matrix_rank(D)

4

# Task 13

In [29]:
D_inv = (D_inv > 0).astype(int)
D_inv

array([[1, 0, 0, 1],
       [1, 0, 0, 1],
       [0, 1, 1, 0],
       [1, 0, 0, 1]])

In [30]:
E = np.where(D_inv, B, C)
E

array([[  5,  12,  14,  32],
       [ 14,   5,  13, 122],
       [  4,  86, 149,  10],
       [ 32,   2,   9, 302]])